"use client";

import { useMemo, useState } from "react";
import type { ContentBlock, ProductContent } from "@/lib/pricing-api";
import { FileText, PenTool, LayoutTemplate, Info } from "lucide-react";

// Renders the copyright-safe editorial content (generated by app.build_spec_content) as the
// education tabs the direction calls for — Product Spec · Artwork Spec · Templates.

const TABS = [
  { key: "sections", label: "Product Spec", icon: FileText },
  { key: "artwork", label: "Artwork Spec", icon: PenTool },
  { key: "templates", label: "Templates", icon: LayoutTemplate },
] as const;

// Content items may be plain strings OR richer card objects ({name, ideal:[...]}) — coerce both so
// an unexpected object shape is never handed to React as a child (which throws).
type LooseItem = string | { name?: string; ideal?: string[] } | null | undefined;

function asCard(item: LooseItem): { name: string; ideal: string[] } | null {
  if (typeof item === "string") return item ? { name: item, ideal: [] } : null;
  if (item && typeof item === "object") {
    const name = typeof item.name === "string" ? item.name : "";
    const ideal = Array.isArray(item.ideal)
      ? item.ideal.filter((x): x is string => typeof x === "string")
      : [];
    if (name || ideal.length) return { name, ideal };
  }
  return null;
}

function Block({ block }: { block: ContentBlock }) {
  const items: LooseItem[] = "items" in block ? (block.items as LooseItem[]) : [];
  const cards = items.map(asCard).filter((c): c is { name: string; ideal: string[] } => c !== null);
  const isCards = block.type === "cards" || cards.some((c) => c.ideal.length > 0);

  return (
    <div className="flex flex-col gap-3">
      {block.title && (
        <h3 className="text-sm font-semibold text-ink">{block.title}</h3>
      )}

      {block.type === "keyvalue" ? (
        <dl className="rounded-lg border border-border divide-y divide-border overflow-hidden">
          {block.rows.map((row, i) => (
            <div
              key={i}
              className="grid grid-cols-1 sm:grid-cols-[minmax(0,180px)_1fr] gap-1 sm:gap-4 px-4 py-3 odd:bg-surface-muted/40"
            >
              <dt className="text-xs font-semibold text-ink-muted uppercase tracking-wide">
                {row.k}
              </dt>
              <dd className="text-sm text-ink-secondary leading-relaxed">{row.v}</dd>
            </div>
          ))}
        </dl>
      ) : isCards ? (
        <div className="grid gap-3 sm:grid-cols-2">
          {cards.map((c, i) => (
            <div key={i} className="rounded-lg border border-border p-4">
              {c.name && (
                <p className="text-sm font-semibold text-ink mb-1.5">{c.name}</p>
              )}
              {c.ideal.length > 0 && (
                <ul className="flex flex-col gap-1">
                  {c.ideal.map((line, j) => (
                    <li key={j} className="flex gap-2 text-xs text-ink-secondary leading-relaxed">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-brand-400" />
                      <span>{line}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      ) : (
        <ul className="flex flex-col gap-2">
          {cards.map((c, i) => (
            <li key={i} className="flex gap-2.5 text-sm text-ink-secondary leading-relaxed">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-400" />
              <span>{c.name}</span>
            </li>
          ))}
        </ul>
      )}

      {block.note && (
        <div className="flex gap-2 rounded-lg bg-brand-50 border border-brand-100 px-3 py-2.5">
          <Info className="w-4 h-4 text-brand-500 shrink-0 mt-0.5" />
          <p className="text-xs text-brand-700 leading-relaxed">{block.note}</p>
        </div>
      )}
    </div>
  );
}

export function ProductContent({ content }: { content: ProductContent }) {
  const available = useMemo(
    () => TABS.filter((t) => (content[t.key]?.length ?? 0) > 0),
    [content]
  );
  const [active, setActive] = useState<(typeof TABS)[number]["key"] | null>(null);

  if (available.length === 0) return null;
  const current = active ?? available[0].key;
  const blocks = content[current] ?? [];

  return (
    <section className="mt-16">
      <div className="rounded-2xl border border-border bg-white overflow-hidden">
        {/* Tab bar */}
        <div className="flex border-b border-border overflow-x-auto">
          {available.map((t) => {
            const Icon = t.icon;
            const on = t.key === current;
            return (
              <button
                key={t.key}
                type="button"
                onClick={() => setActive(t.key)}
                className={`flex items-center gap-2 px-5 py-3.5 text-sm font-medium whitespace-nowrap border-b-2 -mb-px transition-colors ${
                  on
                    ? "border-brand-500 text-brand-700"
                    : "border-transparent text-ink-muted hover:text-ink"
                }`}
              >
                <Icon className="w-4 h-4" />
                {t.label}
              </button>
            );
          })}
        </div>

        {/* Panel */}
        <div className="p-6 sm:p-8 flex flex-col gap-8">
          {blocks.map((block, i) => (
            <Block key={i} block={block} />
          ))}
        </div>
      </div>
    </section>
  );
}
